language: node_js
node_js:
    - "7.10.0"
install:
    - npm install
script:
    - npm test
services:
  - postgresql
cache: 
  - npm install
before_script:
  - createdb hello-books --username=postgres
- sequelize db:migrate